version: '3.9'

services:
  web:
    image: frontend:latest
    restart: always
    ports:
      - 80:80
    depends_on:
      - api
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  api:
    image: backend:latest
    restart: always
    ports:
      - 5005:5005
    command: poetry run uvicorn src.app:app --host 0.0.0.0 --port 5005
    env_file:
      - .env